server:
  port: ${API_GATEWAY_PORT}

tradex:
  services:
    auth: lb://auth-service
    market: lb://market-service

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 10s

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /auth/v3/api-docs
      - name: Market Service
        url: /market/v3/api-docs
